CREATE TABLE `board` ( 
	`no` 		INT 			AUTO_INCREMENT PRIMARY KEY,
	`id` 		VARCHAR(64) 	UNIQUE,
	`title` 	VARCHAR(100) 	NOT NULL,
	`writer` 	VARCHAR(100) 	NOT NULL,
	`content` 	TEXT			NULL,
	`created_at`	TIMESTAMP		DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP		DEFAULT CURRENT_TIMESTAMP
									ON UPDATE CURRENT_TIMESTAMP

);