CREATE TABLE `user` (
	`no` 		INT 			AUTO_INCREMENT PRIMARY KEY,
	`id` 		VARCHAR(64) 	UNIQUE,
	`username`	VARCHAR(100)	UNIQUE,
    `password` 	VARCHAR(100) 	NOT NULL,
    `name` 		VARCHAR(100)	NOT NULL,
    `email`		VARCHAR(100)	NOT NULL,
	`created_at`	TIMESTAMP		DEFAULT CURRENT_TIMESTAMP,
	`updated_at`	TIMESTAMP		DEFAULT CURRENT_TIMESTAMP
									ON UPDATE CURRENT_TIMESTAMP

);